<?php
/**
 * Created by IntelliJ IDEA.
 * User: vjcspy
 * Date: 6/11/16
 * Time: 3:14 PM
 */

namespace Modules\IzShop\Http\Controllers\Products;


use Illuminate\Http\Request;
use Modules\IzShop\Http\Controllers\DataTable\DataTableWithMagentoApiAbstractController;

class ProductController extends DataTableWithMagentoApiAbstractController {

    public function getIndex(Request $request) {
        $this->magentoSearchApi->setApiUrl("http://mage1.dev/rest/v1/xretail/xproduct");

        return parent::getIndex($request); // TODO: Change the autogenerated stub
    }
}